// MESS WALLAH - Icon Mappings
// Centralized icon imports to avoid conflicts between lucide-react and react-icons

import {
  FiUser as User,
  FiUserCheck as UserCheck,
  FiMail as Mail,
  FiPhone as Phone,
  FiMapPin as MapPin,
  FiCalendar as Calendar,
  FiEdit3 as Edit3,
  FiSave as Save,
  FiX as X,
  FiCamera as Camera,
  FiShield as Shield,
  FiBell as Bell,
  FiKey as Key,
  FiStar as Star,
  FiHome as Home,
  FiCreditCard as CreditCard,
  FiTrendingUp as TrendingUp,
  FiHeart as Heart,
  FiClock as Clock,
  FiCheckCircle as CheckCircle,
  FiEye as Eye,
  FiEyeOff as EyeOff,
  FiSettings as Settings,
  FiDownload as Download,
  FiUpload as Upload,
  FiMenu as Menu,
  FiSearch as Search,
  FiFilter as Filter,
  FiSliders as Sliders,
  FiUsers as Users,
  FiWifi as Wifi,
  FiLock as Lock,
  FiGift as Gift,
  FiShare2 as Share2,
  FiChevronRight as ChevronRight,
  FiChevronDown as ChevronDown,
  FiChevronLeft as ChevronLeft,
  FiChevronUp as ChevronUp,
  FiArrowLeft as ArrowLeft,
  FiArrowRight as ArrowRight,
  FiPlus as Plus,
  FiMinus as Minus,
  FiInfo as Info,
  FiAlertTriangle as AlertTriangle,
  FiAlertCircle as AlertCircle,
  FiMessageCircle as MessageCircle,
  FiMessageSquare as MessageSquare,
  FiSend as Send,
  FiFileText as FileText,
  FiFile as File,
  FiFolder as Folder,
  FiImage as Image,
  FiVideo as Video,
  FiMusic as Music,
  FiMic as Mic,
  FiPlay as Play,
  FiPause as Pause,
  FiRefreshCw as RefreshCw,
  FiMaximize2 as Maximize,
  FiMinimize2 as Minimize,
  FiScissors,
  FiClipboard,
  FiCopy as Copy,
  FiScissors as Cut,
  FiClipboard as Paste,
  FiTrash as Trash,
  FiTrash2 as Trash2,
  FiTrash2 as Delete,
  FiEdit as Edit,
  FiEdit2 as Edit2,
  FiExternalLink as ExternalLink,
  FiLink as Link,
  FiLink2 as Link2,
  FiAnchor as Anchor,
  FiBookmark as Bookmark,
  FiTag as Tag,
  FiHash as Hash,
  FiAtSign as AtSign,
  FiPercent as Percent,
  FiDollarSign as DollarSign,
  FiCoffee as Coffee,
  FiSun as Sun,
  FiMoon as Moon,
  FiCloud as Cloud,
  FiCloudRain as CloudRain,
  FiZap as Zap,
  FiBattery as Battery,
  FiPower as Power,
  FiMonitor as Monitor,
  FiSmartphone as Smartphone,
  FiHardDrive as HardDrive,
  FiServer as Server,
  FiDatabase as Database,
  FiWifi as WiFi,
  FiAward as Award
} from 'react-icons/fi';

// Export all icons for easy importing
export {
  User, UserCheck, Mail, Phone, MapPin, Calendar, Edit3, Save, X, Camera,
  Shield, Bell, Key, Star, Home, CreditCard, TrendingUp, Heart,
  Clock, CheckCircle, Eye, EyeOff, Settings, Download, Upload, Menu,
  Search, Filter, Sliders, Users, Wifi, Lock, Gift, Share2,
  ChevronRight, ChevronDown, ChevronLeft, ChevronUp, ArrowLeft, ArrowRight,
  Plus, Minus, Info, AlertTriangle, AlertCircle, MessageCircle, MessageSquare,
  Send, FileText, File, Folder, Image, Video, Music,
  Mic, Play, Pause,
  RefreshCw, Maximize, Minimize, Copy, Cut, Paste, FiScissors, FiClipboard,
  Trash, Trash2, Delete, Edit, Edit2, ExternalLink, Link, Link2,
  Anchor, Bookmark, Tag, Hash, AtSign, Percent, DollarSign,
  Coffee, Sun, Moon, Cloud, CloudRain,
  Zap, Battery, Power, Monitor, Smartphone,
  HardDrive, Server, Database, WiFi, Award
};
